CREATE DATABASE IF NOT EXISTS netpoe_remote
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE netpoe_remote;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('superuser', 'user') NOT NULL DEFAULT 'user',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS routers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  router_name VARCHAR(100) NOT NULL,
  ip_address VARCHAR(45) NOT NULL,
  api_user VARCHAR(100) NOT NULL,
  api_pass VARCHAR(255) NOT NULL,
  api_port SMALLINT UNSIGNED NOT NULL DEFAULT 8728,
  public_host VARCHAR(255) NULL,
  remote_port SMALLINT UNSIGNED NOT NULL DEFAULT 8080,
  remote_nat_comment VARCHAR(100) NOT NULL DEFAULT 'DYNAMIC_REMOTE_MODEM',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_routers_user
    FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  INDEX idx_routers_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
